---

- hosts: webserver
  vars_files:
    - vars/play_webserver.yml

  tasks:
  - name: Add drupal group
    group:
      name: drupal
      state: present

  - name: Add drupal core owner
    user:
      name: "{{drupal_core_owner}}"
      comment: Drupal core owner
      group: drupal

- hosts: webserver
  become: yes
  vars_files:
    - vars/play_webserver.yml
  roles:
    - geerlingguy.apache
    - geerlingguy.git
    - geerlingguy.mysql
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - geerlingguy.drush
    - geerlingguy.drupal

- hosts: webserver
  vars_files:
    - vars/play_webserver.yml

  tasks:
  - name: Fix permissions
    script: files/fixperms.sh --drupal_path="{{ drupal_core_path }}" --drupal_user="{{ drupal_core_owner }}"