---

- hosts: webserver
  become: yes
  roles:
    - geerlingguy.apache
    - geerlingguy.git
    - geerlingguy.mysql
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - geerlingguy.drush
    - geerlingguy.drupal
    - fix-perms
