---

  - src: geerlingguy.apache
  - src: geerlingguy.git
  - src: geerlingguy.mysql
  - src: geerlingguy.php
  - src: geerlingguy.php-mysql
  - src: geerlingguy.composer
  - src: geerlingguy.drush
  - src: geerlingguy.drupal